### ISSUE TITLE
Issue with 7.62 NATO ammo and with new/stacking headgear

### ISSUE THREAD

**Issue by Styrkyr** [AthenaSulisMinerva/CombatExtendedFastTrack#124]
Throws up a heap of errors and throws a purple box around characters heads that have multiple headgear pieces equipped. Logs included

https://gist.github.com/3ae137b6c296561a7168c51ea187b60d

**Comment by sumghai** [comment]
We generally recommend that you post one question per issue, as it makes it easier for us to tackle them separately.

Usually, our advice to new users who encounter errors is to do some troubleshooting on their own first, rather than sending us a log file and be done with it.

Is this happening to an existing savegame, or to a new game?

Can you try the following?:
- Core and original CE only (not FastTrack)
- Core and CE FastTrack only
- Slowly add your other mods back in until you find the specific mod(s) causing the issue

**Comment by sumghai** [comment]
Related to #127 and #130.
