### ISSUE TITLE
RImmu-Nation Helmet and Vest RHA Values

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#125]
Hi there fast track team! I noticed that rimmunation RHA values were very off with old sharp/RHA protection values. Ive made a temporary fix on steam if you are interested. It only adjusts the material effect multiplier and base sharp and blunt armor ratings. It supports most factions added. 
Its not an extensive fix and just makes some vests and helmets slightly better and worse than composite helmets. the M1 helmet uses similar stats to the vanilla simple helmet and is highly dependent on material. 
![6b4b1017f3ec58a590c4ecf52d652c81](https://user-images.githubusercontent.com/57470753/68522828-fd178000-02ea-11ea-87f9-ccaa82d28ab5.png)

**Comment by Theblessedwant** [comment]
I have further made a temporary patch for the factions here, ill upload it onto steam once done
![9d34fa29725c0b76c80d95ecd0754d4c](https://user-images.githubusercontent.com/57470753/68522867-b2e2ce80-02eb-11ea-83df-893a52ea1455.png)

**Comment by sumghai** [comment]
Looks neat!

Could you do this as a Github pull request instead? It'll be easier for us to review changes and merge them into the repo (whereas with Steam, we'd have to subscribe, extract the files, unsubscribe and do lots of doohickey whatsits to integrate them into the existing patches).

**Comment by Theblessedwant** [comment]
oh im not sure how to do that haha, pretty new to github

**Comment by sumghai** [comment]
After seeing your recently attempt at forking on GitHub, I think I'll manually go through your Steam version instead.

Please let us know when you've finished, and I'll get to it as soon as I can.

**Comment by sumghai** [comment]
@Theblessedwant I managed to get hold of that zip file you accidentally uploaded to the upstream repo.

Are you happy for me to start integrating these helmet and vest RHA values into CE:FT? Or do you need to tweak them a little more?

**Comment by Theblessedwant** [comment]
im fine with the values as is

**Comment by Theblessedwant** [comment]
you may edit them as you wish

**Comment by sumghai** [comment]
Okay, I'll get on this ASAP.

**Comment by Theblessedwant** [comment]
I have noticed that if i applied realistic armor values to the Last Man Merc tanks, it appears to make them literally unkillable, the realistic value i choose was 120mm RHA value, based on wikipedia T-55 hull armor values. I thought the turret armor values were too high and therefore chose the hull.
Also noticed that 20x102mm NATO rounds and other cannon rounds have extremely low penetrations, funnily enough even lower than pistol rounds.

**Comment by sumghai** [comment]
> I have noticed that if i applied realistic armor values to the Last Man Merc tanks, it appears to make them literally unkillable, the realistic value i choose was 120mm RHA value, based on wikipedia T-55 hull armor values. I thought the turret armor values were too high and therefore chose the hull.

I see, thanks!

> Also noticed that 20x102mm NATO rounds and other cannon rounds have extremely low penetrations, funnily enough even lower than pistol rounds.

That would probably be because CE:FT first introduced the 20x102mm NATO rounds way back in v1.0.1.5-FT-004, and they haven't been updated (yet) to the new armor penetration system in 1.6.

**Comment by Theblessedwant** [comment]
In regards to the balancing of the armors, i gave plate carriers slightly lower blunt protection as compared to other body armors like the IBA or russian 6b23, Plate carriers afterall are simply a ballistic plate in a pouch with some kevlar backing at times.

**Comment by sumghai** [comment]
Apologies for the delay, @Theblessedwant - I've finished integrating your patches into our existing ones.

Notes:
* I omitted the Kurin ones because we already brought some of the new stats over from upstream
* I also rewrote your contribution so that each item is patched independently, rather than grouped by similar stats; while admittedly less efficient than what you had, patching each item independently makes it easier to review values, as well as being more resilient to item removals in the main Rimmu-Nation or Red Horse Faction mods (i.e. if Chicken Plucker decides to remove any item for any reason, the failed patch is less likely to have a knock-on effect on other patched items)

Finally, I've tested the rewritten patches myself, and can confirm that they behave exactly as your original version on Steam did. So I think I can call this a wrap.

If there are any issues, feel free to reopen this ticket.

Many thanks for your help!
