### ISSUE TITLE
You broke all headgear shit for certain mods

### ISSUE THREAD

**Issue by BUTTERSKY11** [AthenaSulisMinerva/CombatExtendedFastTrack#129]
All vanilla hats and modded hat are fricking broken with certain mods and are replaced with PURPLE SQUARES, when you are done with 1.6 please fix this issue.

Update: Only a couple of mods have this issue due to their cothing systems.

**Yes Yes Mods List (mods that don't shit on game):**
Vanilla Armor Expanded
Vanilla Armor Expanded
Spartan Foundary 

**No No Mods List (mods that shit on game):**
Prisoner Outfits
Rimmunation

**Mods that just make the game unplayable**
RPG Inventory CE

**Comment by BUTTERSKY11** [comment]
also, way too many people also have this issue in the steam comments section but I know you don't read that just like how they don't read to post issues here

**Comment by Theblessedwant** [comment]
Calm down, this is an issue with the original CE as well due to the new layering system. The Dll used previously by these mods utilized its own layer system, the north, south ,east ,west system as shown within my issue. A simple fix is to remove said dll and it will work again

**Comment by BUTTERSKY11** [comment]
Sorry, but I was sort of stress, it took so long to get my save to work again, hours and hours wasted on efforts that I thought were futile, I care way too much for my saves since I lost my saves before.

**Comment by sumghai** [comment]
As frustrated as you may be, there is absolutely **no excuse** to take your anger out on other people, especially when these changes came from the upstream CE project, rather than any (perceived) malicious intent by the CE:FT team.

Seeing as there is a more cordial discussion of this issue in #130, I'm closing this ticket so that we can consolidate things there.
