### ISSUE TITLE
[NL] Facial Animation not working

### ISSUE THREAD

**Issue by PrincessUnikitty** [AthenaSulisMinerva/CombatExtendedFastTrack#133]
https://steamcommunity.com/sharedfiles/filedetails/?id=1635901197

Fix Plz

**Comment by Theblessedwant** [comment]
Facial animation messes with the face layers and uses jobs for facial animations. Im not sure if CE edits the jobs but know that it causes issues with anything that changes the face layers. As is the case with facial animation. Unfortunately this will require an entire rewrite of the assembly code for facial animations and there is not much the CE FT team can do.

**Comment by sumghai** [comment]
When raising issues on Github, it is important that you describe the problem as clearly as possible and provide supporting information, which you have failed to do:

* To begin with, "Can't use this mod" is an extremely vague title; you should have clearly stated you were having problems specifically with the [NL] Facial Animation mod, instead of simply throwing a link and having others figure it out from context

* Secondly, you need to specifically describe what the actual problem is. Is the mod causing the game to crash? Do strange text appear in the game UI? Are textures missing? Or by "can't use", do you mean that you physically can't download the mod at all in the first place?

* Thirdly, you did not specify which version of the base game, CE:FT and this mod you were running.

* Finally, "Fix Plz" is as vague as requests go. If you cannot describe your problem properly, we cannot understand (let alone fix) it

All that being said, the cause of this problem is that the upstream CE mod (which CE:FT is derived from) was updated to version 1.6, which introduces new apparel and draw layers for faces/heads. Unfortunately, many third-party mods have not been updated to recognize the new layers introduced by CE or CE:FT 1.6, and so it is the responsibility of the author of Facial Animations to update his/her own mod to support this new feature.

Personal comment - I've noticed that a significant portion of Facial Animation's users are Japanese or non-native English speakers. While we understand that there are difficulties with language barriers, please make an effort in the future to describe and articulate issues in a clear and informative manner.
