### ISSUE TITLE
Rimmunation Parka, Jacket and trenchcoat values

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#139]
Hi there CE FT team, ive added Parkas and jackets to take into account the new effect multiplier added for Vanilla parkas and dusters. Ill add the factions here once im done with them

[Rimmunation Parkas.txt](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/files/3844507/Rimmunation.Parkas.txt)

**Comment by sumghai** [comment]
Much obliged as always! Looking forward to seeing the faction patches too.

**Comment by Theblessedwant** [comment]
Id like to add that there is  a missing patch for  layers within the  Rimmu-Nation belts and Backpacks
Im not sure if this thingdef  works you  are free to  edit  as  you wish
[Rimmunation Accessories.txt](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/files/3846936/Rimmunation.Accessories.txt)

**Comment by sumghai** [comment]
> Id like to add that there is a missing patch for layers within the Rimmu-Nation belts and Backpacks

Noted! This must be one of the new Webbing layers added by the upstream CE repo.

**Comment by Theblessedwant** [comment]
oh uh also i accidentally replaced the  webbings with operation instead of  li,

**Comment by Theblessedwant** [comment]
[RNC_CE_Patch_Apparel_Belts_corrected.txt](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/files/3846967/RNC_CE_Patch_Apparel_Belts_corrected.txt)
Here is the corrected one i hope

**Comment by sumghai** [comment]
I'm currently busy with another set of patches, but I'll talk to Athena and see if we can slot these changes for the release after the next one.

**Comment by AthenaSulisMinerva** [comment]
Hey @Theblessedwant,

After discussing with @sumghai, we'd like to offer you an invitation to be a contributor, which would allow you to directly make changes and push commits to this repo without having having to make pull requests. I've already sent you an invite via an email link.

If you do accept, here's how you would set up your work environment

* Download and install GitHub Desktop

* Clone the CombatExtendedFastTrack repo to your computer; this will be your local working copy

* Because we all work in different time zones, make sure that you frequently keep your local working copy in sync:

![Annotation 2019-11-16 222355](https://user-images.githubusercontent.com/49829079/68994606-ced40a80-08bf-11ea-9c20-f5d1341774ca.png)

* You can make periodic changes to the contents of the local folder (for example, you test some modified XML files in your actual RimWorld mod folder, then drag & drop them into the right subfolder(s) inside your local copy of CombatExtendedFastTrack)

* To make a commit associated with a particular issue, tick the file(s) you want to include at the top of the **Changes** list:
![Annotation 2019-11-16 220605](https://user-images.githubusercontent.com/49829079/68994378-4eaca580-08bd-11ea-9910-d116d0d9a2d5.png)

* Then, go down and type a summary and a description message explaining what this commit is for; I recommend adopting a consistent manner for filling in both fields:
  * The **Summary** section should be no longer than 50 characters, and start with a imperative word (e.g. Add, Change, Update, Remove, Tweak, Rebalance, Overhaul)
  * The **Description** section can be a bit longer, explaining the details of what you've added/changed; @sumghai and I usually just write `For #<issue number>` or `Affects #<issue number as a consequence of #<another issue>`, as this will automatically associate the commit with a particular issue number on the GitHub website, which makes it easier to track progress in each issue we tackle
  * Generally, we prefer to associate commits with specific issues, but occasionally, if you have a very good reason, you can get away with not tagging the issue number in your issue description
![Annotation 2019-11-16 220805](https://user-images.githubusercontent.com/49829079/68994418-aba85b80-08bd-11ea-9153-0281b2cf9ba2.png)

* Once you hit the `Commit to master` button, you can go back and keep choosing file(s) to commit

* When you have finished making your commits, sync your repo again to make sure they get pushed to master

Here's an example of how one of my typical commits ends up being tagged in an existing issue:

![Annotation 2019-11-16 222731](https://user-images.githubusercontent.com/49829079/68994660-646f9a00-08c0-11ea-9a05-381308b4a8c7.png)

![Annotation 2019-11-16 223005](https://user-images.githubusercontent.com/49829079/68994675-aef11680-08c0-11ea-9f89-fa3ba1c23fea.png)

---------------------

There are plenty of guides and tutorials on the internet on how to work with GitHub repos and good commit/housekeeping habits, but hopefully this crash course will help get you started.

Sound good?

**Comment by Theblessedwant** [comment]
ah i just read this, ill get it set up once my exams are over, in the middle of uni end of semester exams

**Comment by Theblessedwant** [comment]
and i am fairly busy with university so as much as  i would love to be  a contributor, i dont think i can make regular commits within this mod.

**Comment by AthenaSulisMinerva** [comment]
@Theblessedwant - Don't worry, we're totally okay if you only make the occasional or even a one-off series of commits. Setting you up as a contributor simply leaves the door open for the future, in case you suddenly have time or have a very pressing bug to help fix.

@Freedom187, @sumghai and I all have day jobs and families, which means limited time for modding. In fact, @sumghai is actually stuck in a country with dodgy internet access, where on good days he'd be lucky to be able to connect to GitHub, never mind the rest of the internet!

**Comment by sumghai** [comment]
Okay, I've patched the shell layer apparel from RN Clothing.

Next up are the faction mods.

**Comment by sumghai** [comment]
@Theblessedwant all RN Clothing, RH Furniture and RH Faction parkas, jackets and trenchcoats should be patched now. I skipped out on Ghille Suits since I didn't see them being patched your TXT files.

Please let me know if these are good to go.

**Comment by sumghai** [comment]
Marking this one as done.
