### ISSUE TITLE
startup issue both with synthamide and Ratkins

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#142]
![9ba0b88c119ffb650579a449026f5075](https://user-images.githubusercontent.com/57470753/68861279-348c8f00-0726-11ea-8eb7-2aa9aa494641.png)

**Comment by sumghai** [comment]
I'll get on this as soon as I can.

**Comment by Theblessedwant** [comment]
Disregard the syntahmide patch , its working, it issue lies within the ratkin  patch

**Comment by sumghai** [comment]
Roger that - I just figured out that there was nothing wrong with the Rimefeller Synthamide patch on my end, either.

As for NewRatkinPlus, this is very bizarre, because I can't reproduce that error on my end, even after testing it with the latest Steam release of the original Ratkin mod. 

I'm currently only running:
* Core
* Combat Extended (the display name for CE:FT)
* Humanoid Alien Races 2.0
* NewRatkinPlus

Can you try reproducing the issue with this modlist?

Also, the current iteration of the Ratkin patches are in this directory, and have not changed since FT-005:

https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/tree/master/Patches/NewRatkinPlus

**Comment by sumghai** [comment]
@Theblessedwant - I still cannot reproduce this issue. Can you please try the mod order I mentioned, as well as making sure you have the most current Ratkin patches from CE:FT?

**Comment by Theblessedwant** [comment]
i think it was an issue with my load order, disregard this.
