### ISSUE TITLE
DLL fix for detours within rimmunation and hopefully other similar pink boxes

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#143]
So with the help of a coder on discord, he has managed to detour...the  detour of rimmu-nation thus nulling  it in a sense, it basically just overwrites that specific dll with the vanilla code to allow CE to load proper. I have included the fix here with his permission.
[DontWearPinkSquares.zip](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/files/3847334/DontWearPinkSquares.zip)
![315938d899ee702fbf99f2c33eea3fa6](https://user-images.githubusercontent.com/57470753/68872789-8e4a8480-0739-11ea-86dd-dbb28b1cec7c.png)

**Comment by Theblessedwant** [comment]
All credit goes to Dyrewolf for helping me with  this issue

**Comment by sumghai** [comment]
I'll take a closer look when I get off work tonight.

Is this something we have to package with CE:FT, or is it for third-party modders to include with their own mods?

**Comment by Theblessedwant** [comment]
It has to be loaded before* rimmu-nation is loaded, it basically detours any dll that is GraphicApparelDetour, back to the vanilla dll

**Comment by Theblessedwant** [comment]
I'll test it by putting it into the FT version ive downloaded and see if i get any errors
will get back to you soon

**Comment by Dyrewulfe** [comment]
Hi, figured I'd chime in here, since I wrote that thing. I'd initially thought it was load order dependent(Apparently I goofed somewhere on that test), but it's not.

The gist of it, is it searches the list of loaded assemblies for that particularly detour DLL, and patches it's detour injection method with a Harmony detour. Simply including it in the Assemblies should suffice. Another option would be to incorporate it into your Harmony patch set directly.  If it's not needed, it'll do nothing.

Source attached:
[No_Pink_Squares.cs.txt](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/files/3849762/No_Pink_Squares.cs.txt)

WTFPL License

**Comment by Dyrewulfe** [comment]
I did some investigation, and apparently this is an old detour made by Jecrell, and it's in quite a few mods. I'm going to tidy this up and PR it upstream.

**Comment by AthenaSulisMinerva** [comment]
Hi @Theblessedwant and @Dyrewulfe, thanks for pitching in to help with this issue!

I am somewhat concerned about having an additional DLL in our assembly, especially as I'm not sure how we would integrate that source code into the main CE code we've pulled from upstream.

**Comment by Dyrewulfe** [comment]
I've made the PR, and spoken with NIA. This fix should be available from upstream in the near future.

**Comment by AthenaSulisMinerva** [comment]
Ah, having it being accepted upstream works out perfectly for us.

@sumghai, thoughts?

**Comment by Dyrewulfe** [comment]
#899

**Comment by sumghai** [comment]
Since these changes are coming from upstream, no further action is required on our part.
