### ISSUE TITLE
Alpha animals CE patch

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#146]
Greetings CE FT Team, once again due to my absolute inability to use github to  issue a pull request to a fork project I present to you, Alpha animals CE patch, it re balances all leathers as well as issue body types to the animals with alpha animals. I used the old alpha animals CE patch made by Saeebi and updated it to work with CE 1.6 as well as adjust leather protection values.
edit:Forgot to update the armor pen types, doing it now

**Comment by Theblessedwant** [comment]
[Duck's CE patch.zip](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/files/3849758/Duck.s.CE.patch.zip)
Should be corrected

**Comment by sumghai** [comment]
Noted with thanks! I'll see when I can fold these changes in.

**Comment by sumghai** [comment]
@Theblessedwant - Patches are up and tested (mostly) OK on my end, other than a couple of things:

* Mantraps (`AA_Mantrap`) haven't been patched

* The [Projectiles patches](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/blob/master/Patches/Alpha%20Animals/AlphaAnimals_CE_Patch_Projectiles.xml) currently still use the deprecated `armorPenetrationBase` stat

**Comment by sumghai** [comment]
I've just added a rough-and-ready patch for Mantraps (`AA_Mantrap`), basing it on the Needlepost since both are tall, sentient plants.

**Comment by sumghai** [comment]
...and I've tweaked the projectile stats with some preliminary armor penetration values.

Some projectiles may or may not have sharp or blunt effects - for instance, I've reasoned that the web projectiles can't pierce armor, but can at least stun targets through (very limited) blunt trauma.

This will have to do for now - @Theblessedwant, you can refine these values later if you wish.

**Comment by codacodium** [comment]
Unfortunately, the patch in the latest 1.0.1.8-FT-009 version is still not fully functional nor balanced. I understand that you all are very busy, so I would be willing to turn this into a paid commission to make this into a priority. If that is something you are comfortable with, please let me know the best way to contact you to set this up.

Summary of problems:
1. Animals lack CE stats like armor penetration and armor values, resulting in log error spam and creatures being weaker than they should be. 
1b. Present animal stats out of balance with the modded CE core animals across the board, with weaker attacks and very low armor ratings. For example, the black hive insectoids are supposed to be upgraded versions of the core megascarabs/megaspiders/etc, but the patch makes them worse than their CE-improved core counterparts.  

Ideally I would like to see the CE-patched AA creatures more/less powerful to CE-patched core creatures to roughly the same proportions as base AA creatures are to base vanilla creatures, if that makes sense.

2. Certain projectiles and items appear to be broken. The galatross horn doesn't have CE melee weapons stats (ideally it should be disabled as a weapon to be in line with CE's thrumbo horn / elephant tusk) while black hive projectiles do multiple hundred points of blunt damage instead of some acid damage one would expect. These are just the ones I've found so I would assume other animal projectiles have problems as well. I have not checked if the modded leathers are in line with the CE leathers, balance or stat wise.

3. No support for animals referenced by Advanced Biomes. They lack patches altogether, which, while I understand may not be in the scope of AA integration, I would like to humbly request to be implemented.
3a) To piggyback on this (and forgive me if opening a separate issue would have been more appropriate), an Alpha Biomes patch, since the two mods are so tightly integrated.

**Comment by sumghai** [comment]
We're currently on FT-012 already.

No, we are not accepting paid commissions to prioritize certain issues over others.

Due to our much smaller team size, we'll get to the issue when we get around to it.

**Comment by codacodium** [comment]
(Right, FT-12 is the one I meant). 

That's fair enough. If I can get someone to do this or if I get around to doing it myself, I will link the updated patch for y'all to save you some work.
