### ISSUE TITLE
Android Tiers - android stuck picking up & dropping meals

### ISSUE THREAD

**Issue by MK1776** [AthenaSulisMinerva/CombatExtendedFastTrack#149]
Hi FT Team,

I have Android Tiers installed and have encountered the issue of androids repeatedly picking up meals and putting them down. For example, android colonists will stop whatever job they're doing to go pick up a random meal just to put it back down, go back to their job and repeat. 

After hours of going through my mod list, I've found that the removal of CE or CE fast track (I don't run both at the same time) would allow the android to pick up the meal and get back to work. All new games without combat extended do not experience any issues.

**Comment by sumghai** [comment]
@MK1776, I haven't been able to reproduce your issue on my end - my androids only pick up meals when they want to eat, and otherwise do not repeatedly pick up and drop them.

This sounds like another mod is causing this incompatibility. Could you please try starting a savegame with only the following mods?:

* JecsTools 1.1.0.15 (12-14-2018) or newer
* Humanoid Alien Races 2.0 (11 Nov 2019 update)
* CE:FT v1.0.1.8-FT-009

**Comment by sumghai** [comment]
Okay @MK1776, I've just managed reproduced your issue with just the mods I mentioned above - it has something to do with their loadouts:

* **No specified loadout** - The Android picks up just one meal to keep in its inventory, and goes on its merry way
* **Loadout without any meals specified** - The Android gets stuck in the meal pick-up-drop-off loop
* **Load with a meal specified** - The Android picks up the specified meal to keep in its inventory, and goes on its merry way

This seems like a problem with the core CE functionality and Humanoid Alien Races 2.0, in which the loadout rules conflict with the pawn's default behaviour of saving aside a meal as a "packed lunch".

Unfortunately, this sort of thing is outside the CE:FT team's area of expertise, so I suggest you raise this issue to the original CE repo instead.
