### ISSUE TITLE
Glitter Tech Mod

### ISSUE THREAD

**Issue by TheEventHorizon** [AthenaSulisMinerva/CombatExtendedFastTrack#15]
This might too big of a task given the size of the mod. But perhaps it can be a long term goal. 
Mod found here:
https://steamcommunity.com/sharedfiles/filedetails/?id=725576127

**Comment by AthenaSulisMinerva** [comment]
This one's for you to handle for the next release, @sumghai.

**Comment by sumghai** [comment]
Ooh, this will be a doozy, but I'll take a look when I have time.

**Comment by sumghai** [comment]
Currently in the process of contacting Glitter Tech mod author @sam23694 regarding what unique ammo, projectile and damage types he wants for each of his weapons.

**Comment by TheEventHorizon** [comment]
I just wanna say everyone working on this project is amazing! Truly living up to the "fast track" name. If I can help in any way please let me know.

**Comment by TheEventHorizon** [comment]
> 
> 
> Currently in the process of contacting Glitter Tech mod author @sam23694 regarding what unique ammo, projectile and damage types he wants for each of his weapons.

The mod author has not been active on github for quite awhile. I'd recommend contacting them through steam.

**Comment by sumghai** [comment]
I actually contacted sam first through Steam, and had a fruitful discussion with him. Tagging his GitHub username here in this issue is just for the sake of documentation (although admittedly, his no longer updates his GitHub releases as often as his Steam workshop one).

## Summary
- **APB-1 weapons** are plasma / particle beam firearms
  - Plasma ammo cartridges or fuel cells of different calibers
- **EMRG-1** and **MRG-5** weapons are railguns
  - Railgun slugs
  - Power either assumed to be supplied by the weapons themselves, or integrated as part of a slug+power cell cartridge
- **Orion Corp weapons** are simply advanced gunpowder firearms
  - Sam agrees that I can use standard NATO ammo calibers where possible
  - OC Tank cannons should just use existing CE cannon shells
- **Turrets**
  - **EMRG turret** consists of a EMRG-1 railgun jury-rigged to a turret base
  - **Canister turret** described as "A cross between minigun and shotgun, attached to a turret"; essentially a Metal Storm-style weapon?
  - **Automatic mortar** should use the standard vanilla 81 mm mortar; capable of firing several rounds before reloading?
  - **Cluster mortar** may require unique 81 mm mortar with cluster bomb effect
  - **Long range missile turret** resembles a Hydra 70 rocket pod; Hydra rockets are normally unguided, but BAE Systems now produces a version called the [Advanced Precision Kill Weapon System (APKWS)](https://en.wikipedia.org/wiki/Advanced_Precision_Kill_Weapon_System), and successfully used in Afghanistan by the USMC; [a surface-to-surface version is also in development](https://www.defensenews.com/newsletters/digital-show-daily/2018/10/08/not-just-for-aircraft-anymore-this-laser-guided-rocket-kit-can-be-mounted-for-ground-defense/), which is exactly what we want for Glitter Tech
  - **Cruise missile turret** launches a single cruise missile before reloading; ground-launched cruise missiles are exceedingly rare, with the closest real-life equivalent being the Israeli [Delilah-GL](https://en.wikipedia.org/wiki/Delilah_(missile)#Delilah-GL_missile); Glitter Tech version would require a unique caliber
 - No weapons (aside from the OC Pacifier melee staff/knife) are craftable
  - Sam plans to make the weapons craftable in a future update
  - Not required for the first version of the GT CE:FT patch

Okay, I have all the notes I need. Back to patching!

**Comment by TheEventHorizon** [comment]
> I actually contacted sam first through Steam, and had a fruitful discussion with him. Tagging his GitHub username here in this issue is just for the sake of documentation (although admittedly, his no longer updates his GitHub releases as often as his Steam workshop one).
> 
> ## Summary
> * **APB-1 weapons** are plasma / particle beam firearms
>   
>   * Plasma ammo cartridges or fuel cells of different calibers
> * **EMRG-1** and **MRG-5** weapons are railguns
>   
>   * Railgun slugs
>   * Power either assumed to be supplied by the weapons themselves, or integrated as part of a slug+power cell cartridge
> * **Orion Corp weapons** are simply advanced gunpowder firearms
>   
>   * Sam agrees that I can use standard NATO ammo calibers where possible
>   * OC Tank cannons should just use existing CE cannon shells
> * **Turrets**
>   
>   * **EMRG turret** consists of a EMRG-1 railgun jury-rigged to a turret base
>   * **Canister turret** described as "A cross between minigun and shotgun, attached to a turret"; essentially a Metal Storm-style weapon?
>   * **Automatic mortar** should use the standard vanilla 81 mm mortar; capable of firing several rounds before reloading?
>   * **Cluster mortar** may require unique 81 mm mortar with cluster bomb effect
>   * **Long range missile turret** resembles a Hydra 70 rocket pod; Hydra rockets are normally unguided, but BAE Systems now produces a version called the [Advanced Precision Kill Weapon System (APKWS)](https://en.wikipedia.org/wiki/Advanced_Precision_Kill_Weapon_System), and successfully used in Afghanistan by the USMC; [a surface-to-surface version is also in development](https://www.defensenews.com/newsletters/digital-show-daily/2018/10/08/not-just-for-aircraft-anymore-this-laser-guided-rocket-kit-can-be-mounted-for-ground-defense/), which is exactly what we want for Glitter Tech
>   * **Cruise missile turret** launches a single cruise missile before reloading; ground-launched cruise missiles are exceedingly rare, with the closest real-life equivalent being the Israeli [Delilah-GL](https://en.wikipedia.org/wiki/Delilah_(missile)#Delilah-GL_missile); Glitter Tech version would require a unique caliber
> * No weapons (aside from the OC Pacifier melee staff/knife) are craftable
> * Sam plans to make the weapons craftable in a future update
> * Not required for the first version of the GT CE:FT patch
> 
> Okay, I have all the notes I need. Back to patching!

Run into any difficult objects to patch? I'm extremely novice when it comes to programming but I'm more than happy to help in any way I can.

**Comment by AthenaSulisMinerva** [comment]
I'm sure sumghai is still working on the patches, but he does have a very busy day job as an engineer. He'll let us know when he's ready.

(By the way, please don't include the entire quote in your reply, especially if it is very long - I've just edited your last comment. In fact, you don't always need to quote someone when replying)

**Comment by sumghai** [comment]
Sorry for the late response - I was away on a company offsite training program for two weeks.

I've also been quietly working behind-the-scenes to implement a new, minor feature to support Glitter Tech ammo - a special variant of the vanilla `Graphic_StackCount` class called **`CombatExtended.Graphic_StackCountRanged`**. 

Like the vanilla stack count graphic class, it allows the use of multiple subgraphics to represent different quantities of an item in the same stack, but it uses number suffixes in the subgraphic's filenames to determine what is the maximum stack count that can be used per subgraphic before switching to the next subgraphic in the collection.

Here's a concrete example:
- Usually, when you use the vanilla `Graphic_StackCount`, it displays:
  -  `Pistol_a` if the stack count is 1
  -  `Pistol_b` if the stack count is greater than 1 but less than the full stack limit
  -  `Pistol_c` if the stack count is at the full stack limit
- `CombatExtended.Graphic_StackCountRanged` looks at the number suffixes, and displays:
  -  `Pistol_15` if the stack count is between 1 and 15
  -  `Pistol_499` if the stack count is between 16 and 499
  -  `Pistol_500` if the stack count is at the full stack limit of 500

I added this feature for a visual gimmick with the Glitter Tech APB Plasma ammo, because I imagined that plasma fuel cells would contain multiple "shots" in each individual canister, rather than individual one-shot cartridges like for conventional bullets.

The code for the new class should be robust enough for the next release, and I have placeholder graphics for all the Glitter Tech small arms ammo. Other than that, I still need to do CE patches for all the GT turrets.

**Comment by AthenaSulisMinerva** [comment]
That's pretty cool!

Are you also going to update the graphics definitions for all the existing ammo?

**Comment by Taranchuk** [comment]
Can you nerf the automatic mortars via patch? Because if there are automatic mortars on quest maps, then this is a 100% chance that my caravan will be lost and this is my biggest complaint to the mod.

**Comment by sumghai** [comment]
@AthenaSulisMinerva - Nah, that will confuse most users (including myself) who are used to the current behaviour for conventional gunpowder cartridge ammo. As previously mentioned, the new **`CombatExtended.Graphic_StackCountRanged`** class is really only for sci-fi ammo.

@Taranchuk - Which aspect of the auto mortars need to be nerfed? Rate of fire? Accuracy? Range?

A specific description on which aspects to nerf and how would be appreciated.

**Comment by Taranchuk** [comment]
@sumghai Probably accuracy, at least there should be a chance that the mortars would shoot the wrong way.

**Comment by sumghai** [comment]
@Taranchuk - Okay, I should be able to tone down accuracy a bit for CE:FT. You'll probably have to help me test it when the time comes.

**Comment by AthenaSulisMinerva** [comment]
@sumghai - Okay, makes sense.

**Comment by sumghai** [comment]
I've got the EMRG and Cannister turrets working just fine.

However, I'm having problems with the three automatic mortar turrets (Auto, Cluster and EMP):
- Players cannot change ammo type (HE/Incendiary/Antigrain/etc.)
- Mortar turrets have unlimited ammo, rather than being able to be reloaded

I'm currently comparing the GT mortar turrets to both the CE patches for the Core (vanilla) mortars and the automatic grenade launchers from [my own DMGTP mod](https://github.com/sumghai/DefensiveMachineGunTurretPack/); it seems that @sam23694 has structured his XML defs a bit differently from other turret mods, so my usual approaches to CE patching isn't working as well as it should.

I'll keep at it, but if it takes too long, I'm tempted to leave the mortar turrets unpatched until I have more time - I have a backlog of mod compatibility requests to work through.

**Comment by sumghai** [comment]
Automatic mortars are now working. Progress! :)

All mortars have a maximum ammo capacity of 25 mortars, the max stack size of CE 81mm mortar rounds. I've correspondingly reduced the round per salvo from 12 to 5 for the cluster and EMP mortars, as 25 ÷ 5 = 5 salvos means pawns will reload the mortars less often than 25 ÷ 12 ≈ 2.08 salvos; besides, a 12-salvo would be quite wasteful now that players have to learn to conserve ammo.

`ShootingAccuracyTurret` and `AimingAccuracy` are currently set to 0.875 - decent enough against large enemy groups clump together during sieges, but mostly useless against a handful of raiders running and dodging quickly across the map - which should be what we want.

@Taranchuk - please test the following dev version of CE:FT, and confirm that the desired behaviour has been implemented:

https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/archive/e07713dfb8b72a8fa6b2f337615ec3bff349b748.zip

In the meantime, I'm going to move on to patching the missile turrets.

**Comment by sumghai** [comment]
Missile turrets have now been patched (for the most part).

Remaining issues:
- Missile turrets currently fire projectiles up in a parabolic arc like a mortar, instead of a flatter and more direct trajectory; this is because they use `CombatExtended.Verb_ShootMortarCE`, rather than the usual `CombatExtended.Verb_ShootCE` (which require line-of-sight targeting and cannot fire over walls). A comprehensive fix may require a variant of the verb class that allows projectiles to be rendered as directly flying over walls.
- Tweak or create new ammo classes/categories for the various new ammo added to support GT
- Turret `WorkToBuild` rebalance; should be straightforward
- Ammo and projectile textures; also straightforward

**Comment by sumghai** [comment]
I've decided to internally rename most of the Glitter Tech ammo defs to use more generic names and categories, so that they (or at least their textures) can be reused for other third-party mods, without being locked into Glitter Tech-specific descriptions.

**Comment by sumghai** [comment]
This is *just about* done.

The only thing left is a minor QoL improvement for the missile launchers - seeing if I can modify `CombatExtended.Verb_ShootCE` to support `<requireLineOfSight>` so that I can use that class instead of `CombatExtended.Verb_ShootMortarCE` (which fires missiles in a parabolic arc).

**Comment by sumghai** [comment]
Nope, no can do - missile launchers will just have to behave like mortars for now.

Otherwise, everything else seems to be in place, so I reckon we can call this a wrap.
