### ISSUE TITLE
Alpha Animals Crapascular beetle 

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#154]
Seems like there isnt a melee stat for this animal.  Ill have to fix it on my end too 
![fde65c6371f11229b011c10ac0256628](https://user-images.githubusercontent.com/57470753/69009728-35762880-0993-11ea-943f-eda414955f5b.png)

**Comment by sumghai** [comment]
Well, this is bizarre.

The Steam version of Alpha Animals doesn't seem to have Crepuscular Beetles (as well as a few other animals/insects), but the GitHub version does.

**Comment by Theblessedwant** [comment]
eh? Im using the Steam version of Alpha Animals though, maybe they recently removed it?

**Comment by sumghai** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1541721856

I used a Steam Workshop downloader to obtain the Nov 12 update, and the defs in the download were definitely missing Crepuscular Beetles et al.

In any case, since the GitHub version was released at around the same time and does, in fact, include the missing creatures, we should be patching according to that instead.

Let me know when you've got something ready.

**Comment by Theblessedwant** [comment]
[Crapascular_Beetle.txt](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/files/3863570/Crapascular_Beetle.txt)
Heres a CRAPTASTIC beetle, i used the megaspider stats as a template

**Comment by sumghai** [comment]
Patch for Crepuscular Beetles is now up - I've tested and confirm that the beetle works fine in CE:FT.

Would you like me to close this issue, or keep it open for any missing AA creatures yet to be patched?

**Comment by Theblessedwant** [comment]
Issue fixed
