### ISSUE TITLE
Mod that adds back vanilla items removed by CE?

### ISSUE THREAD

**Issue by NickZiggy** [AthenaSulisMinerva/CombatExtendedFastTrack#157]
Is there any known mod that adds back the vanilla items that were removed by the CE devs, namely the autocannon turret, the uranium slug turret, the charge lance and minigun?
I am already working on making the defs myself and was wondering what caliber would you suggest to use for the two turrets. Thank you for updating the armor penetration on the shell defs too.

**Comment by sumghai** [comment]
AFAIK, I don't think there is a mod out there that adds these vanilla items back into CE savegames, and I'm also not entirely sure why these items were removed in the first place, other than "for balance reasons".

As for suggested calibers:

* The autocannon turret could use the [25x137mm NATO](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/blob/master/Defs/Ammo/Shell/25x137mmNATO.xml) shell, which is the same caliber used on the M242 Bushmaster chain gun.

* The uranium slug turret may need a custom caliber, since there is no real-life counterpart (depleted uranium sabot rounds are probably too advanced for this). I'll see if I have the time to come up with something.

* The charged lance could use the [12x64mm Charged](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/blob/master/Defs/Ammo/Advanced/12x64mmCharged.xml) cartridge

* The minigun would usually use the [7.62x51mm NATO](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/blob/master/Defs/Ammo/Rifle/762x51mmNATO.xml) rifle cartridge; in hindsight, I think one of the reasons handheld miniguns were removed from CE is because in real life, miniguns are far too heavy to be hand-wielded, [pop culture media notwithstanding](https://en.wikipedia.org/wiki/Minigun#Fiction_and_popular_culture). The proposed [XM214 Microgun](https://en.wikipedia.org/wiki/XM214_Microgun) would have used the smaller [5.56x45mm NATO](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/blob/master/Defs/Ammo/Rifle/556x45mmNATO.xml) rifle cartridge, but had poorer range and accuracy compared with the 7.62x51mm NATO, and so it never saw the light of day.

**Comment by Theblessedwant** [comment]
I'll work on a mod that adds back the vanilla items into the game. Imho, the autocannon should use the 102x20mm shells, it isnt too OP and it will scale well if VAE ever decideds to add double autocannons. The uranium slug can just use 100mm tank shells added my LMM guns.
I do believe miniguns should be disabled as they are way too bulky to be carried around realistically and the amount of ammo needed to maintain one firing is insane.

**Comment by NickZiggy** [comment]
>in real life, miniguns are far too heavy to be hand-wielded
Which is a ridiculous notion of course to come from the same dev that made power armor increase a pawn's carry weight. Also bionics exist.

**Comment by sumghai** [comment]
> Imho, the autocannon should use the 102x20mm shells, it isnt too OP
AFAIK, the 20x102mm NATO shell is only really used on the M61 Vulcan gatling-style rotary cannon.

If you feel that 25x137mm NATO is still a bit too much, what if I instead created a new ammo def for the [20x128mm Oerlikon](https://en.wikipedia.org/wiki/Oerlikon_20_mm_cannon)? Oerlikon single-barrel autocannons are still in use today.

> The uranium slug can just use 100mm tank shells added my LMM guns or 105 APFSDS uranium SABOT rounds. Which imho, is overkill for anything the game has to offer, APFSDS shots from 105mm guns can penetrate upwards of 400mm RHA which nothing in the game has protection for.
I don't think the uranium slug turret should be using tank or sabot shells, since that would put it in the same performance bracket as the "90mm Flak turret" listed on the CE Gun Stats spreadsheet.

I'd instead suggest also creating a new [30x173mm Oerlikon](https://en.wikipedia.org/wiki/Oerlikon_KCA) caliber, which definitely has[ a real-life depleted uranium slug penetrator ammo variant](https://en.wikipedia.org/wiki/Depleted_uranium#/media/File:30mm_DU_slug.jpg).

**Comment by sumghai** [comment]
> Imho, the autocannon should use the 102x20mm shells, it isnt too OP
AFAIK, the 20x102mm NATO shell is only really used on the M61 Vulcan gatling-style rotary cannon.

If you feel that 25x137mm NATO is still a bit too much, what if I instead created a new ammo def for the [20x128mm Oerlikon](https://en.wikipedia.org/wiki/Oerlikon_20_mm_cannon)? Oerlikon single-barrel autocannons are still in use today.

> The uranium slug can just use 100mm tank shells added my LMM guns or 105 APFSDS uranium SABOT rounds. Which imho, is overkill for anything the game has to offer, APFSDS shots from 105mm guns can penetrate upwards of 400mm RHA which nothing in the game has protection for.

I don't think the uranium slug turret should be using tank or sabot shells, since that would put it in the same performance bracket as the "90mm Flak turret" listed on the CE Gun Stats spreadsheet.

I'd instead suggest also creating a new [30x173mm Oerlikon](https://en.wikipedia.org/wiki/Oerlikon_KCA) caliber, which definitely has[ a real-life depleted uranium slug penetrator ammo variant](https://en.wikipedia.org/wiki/Depleted_uranium#/media/File:30mm_DU_slug.jpg).

**Comment by Theblessedwant** [comment]
Thats a great idea Sumghai, But maybe the rounds is too small? maybe increase it to 40mm Bofors rounds? do those have  DU rounds for them?

> > in real life, miniguns are far too heavy to be hand-wielded
> 
> Which is a ridiculous notion coming from the same dev that made power armor increase a pawn's carry weight. Also bionics exist.

The main issue would be bringing enough ammo for it to be viable. Say you get the realistic weight of a M134 Minigun, thats roughly 85lb or 40kg. Which is your entire pawn's carry weight, Now consider that it uses 7.62x51 NATO, you are only going to be able to carry several hundred rounds tops, meaning that in a firefight, you would be out of ammo in mere seconds. 
Secondly, bionics do not increase your overall carry weight i believe or rather they should. Having a bionic leg isnt going to increase your overall weight when your spine and hips are still bearing the brunt of it all.

**Comment by sumghai** [comment]
According to a copy of the Nammo (formerly Bofors) ammunition catalogue I have on hand, there are no 40mm Bofors variants that have DU penetrators.


>>>in real life, miniguns are far too heavy to be hand-wielded
>>Which is a ridiculous notion coming from the same dev that made power armor increase a pawn's carry weight. Also bionics exist.
>>>The main issue would be bringing enough ammo for it to be viable. Say you get the realistic weight of a M134 Minigun, thats roughly 85lb or 40kg. Which is your entire pawn's carry weight, Now consider that it uses 7.62x51 NATO, you are only going to be able to carry several hundred rounds tops, meaning that in a firefight, you would be out of ammo in mere seconds.

In addition to the ammo capacity issue, there's also the power requirement for driving the minigun - a large lead-acid battery would further reduce the effective ammunition capacity carried by pawns.

The only example of a plausible handheld minigun light enough to carry along with ammo and power source is [Empty Shell LLC's XM556 Microgun](http://www.emptyshell.us/xm556-microgun), chambered in 5.56x45mm NATO - but even then that is still in the prototype stage, and still suffers from the reduced range and accuracy of the 5.56mm caliber.

**Comment by NickZiggy** [comment]
As long as using it requires a pawn to equip a power armor, I think adding the minigun back is fine, at least to preserve the intention of the original game to be Sci-Fi and all the related tropes of it. Just don't make it that heavy if it would prevent a pawn from carrying ammo for it. But from the testing I did by just re-enabling the CE def for the minigun, my pawns could use it with ammunition no problem, as long as they equip a power armor.

>Empty Shell LLC's XM556 Microgun

That actually looks like a toy gun lol.

**Comment by sumghai** [comment]
@NickZiggy, @Theblessedwant - I've added a couple of new ammo definitions that you guys may find useful.

For the Autocannon Turret, use the [20x128mm Oerlikon](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/blob/master/Defs/Ammo/Shell/20x128mmOerlikon.xml).

For the Uranium Slug Turret, use the [30x173mm NATO](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/blob/master/Defs/Ammo/Shell/30x173mmNATO.xml); note that as per the name of the turret, it should only allow DU sabots / slugs, so make sure you also create and use this special AmmoSet (and not the normal AmmoSet containing the other types):

```
<CombatExtended.AmmoSetDef>
	<defName>AmmoSet_30x173mmNATO_UraniumSlugTurret</defName>
	<label>30x173mm NATO</label>
	<ammoTypes>
		<Ammo_30x173mmNATO_Sabot>Bullet_30x173mmNATO_Sabot</Ammo_30x173mmNATO_Sabot>
	</ammoTypes>
</CombatExtended.AmmoSetDef>
```

**Comment by NickZiggy** [comment]
@sumghai Thank you, I will upload what I have so far after the next release of FT

**Comment by sumghai** [comment]
@NickZiggy - Just to clarify, you're releasing your work as a standalone third-party mod that has CE:FT as a dependency, correct?

**Comment by NickZiggy** [comment]
@sumghai Yes, don't raise your expectations too much though, it's my first attempt at modding. So far I've been using miniguns and charge lances in my savefile fine though.

**Comment by NickZiggy** [comment]
Here it is: [https://github.com/NickZiggy/CombatExtended-VanillaRestored](url)

**Comment by NickZiggy** [comment]
Here it is: [https://github.com/NickZiggy/CombatExtended-VanillaRestored](url)

**Comment by sumghai** [comment]
Okay @NickZiggy - I'll close this issue, since it's up to you now as to whether you make use of these new ammo types.

**Comment by NickZiggy** [comment]
Here it is https://github.com/NickZiggy/CombatExtended-VanillaRestored
