### ISSUE TITLE
Invalid texture

### ISSUE THREAD

**Issue by VenomiXeD** [AthenaSulisMinerva/CombatExtendedFastTrack#158]
There's a missing texture for The Gasmask. As it just renders "A box".
![image](https://user-images.githubusercontent.com/32819948/69092262-4c2c8600-0a4c-11ea-8a1c-6f9ae5cb39b2.png)
But all of the others have textures.
![image](https://user-images.githubusercontent.com/32819948/69092280-55b5ee00-0a4c-11ea-803c-28063c937519.png)

Mistake? Because this happens.
![image](https://user-images.githubusercontent.com/32819948/69092304-61091980-0a4c-11ea-9343-535153b6b8aa.png)

Path: Textures/Things/Apparel/GasMask

**Comment by VenomiXeD** [comment]
Spoilers: Seems to happen with quite a lot of textures.
![image](https://user-images.githubusercontent.com/32819948/69092510-cceb8200-0a4c-11ea-9bf3-57e25945c290.png)
![image](https://user-images.githubusercontent.com/32819948/69092517-d2e16300-0a4c-11ea-8470-b25637f2f97d.png)

**Comment by sumghai** [comment]
The Gas Masks were brought in from the upstream CE mod. The north-facing textures are blank because the original CE team intended for the back of a pawn's head to be exposed.

As for the "pink square" missing textures issue, this is because you are also running a third-party mod that uses GraphicsApparelDetour.DLL, which is incompatible with CE's new apparel layers and rendering system. The upstream CE mod already released a fix which hides the pink squares by essentially disabling all copies of GraphicsApparelDetour.DLL it finds - CE:FT has also just got its hands on the code, and will push out an update later this week.
