### ISSUE TITLE
Rimmu-nation PASGT Helmets Recipe Rebalancing

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#162]
So ive taken a look at the helmets, all seems great except that PASGT helmets have  levels of protection similar to that of composite helmets but cost the same as Simple Helmets, Real life PASGT Helmets had kevlar within them so ive changed the cost to use devilweave or with rimefeller installed, Synthamide
Ive used a nested patchoperation find mod to find rimfeller and if it doesnt, it uses regular devilstrand. Im unsure as to how to set recipes to take either devilstrand or synthamide.
[RNC_CE_Patch_PASGT_Helmet Rimfeller.txt](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/files/3864118/RNC_CE_Patch_PASGT_Helmet.Rimfeller.txt)

**Comment by sumghai** [comment]
Okay, I'll take a look tomorrow night.

**Comment by sumghai** [comment]
Your current patch works as described - I tested it both with and without Rimefeller.

If I understand you correctly, you wanted it so that if Rimefeller was installed, players would have the option to craft the helmets using metallic stuff plus either devilstrand or synthamide? That would most likely require overriding RN's recipe maker and replacing it with an explicit crafting recipe, which is a bit complex for us right now.

Let's just use your patch as-is, and revisit the stretch goal at a later date.
