### ISSUE TITLE
Compatibility / Conflicts

### ISSUE THREAD

**Issue by KazTheMercenary** [AthenaSulisMinerva/CombatExtendedFastTrack#163]
Pardon, this is my first time reporting here!  O_O

I've been trying to track down a bug/conflict, and don't appear to be having any luck.  But, right or wrong, I keep coming up with 3 things that people seem to be ATTRIBUTING to this mod.

The first being lack of armor penetration.  I had my suspicions from play, but haven't been able to verify myself.

The second is purple boxes for worn headgear.

The third being double equipment for certain things like gloves, scarves, eyeware... and attempting to remove them appears to duplicate them instead.

I just completed a 20+ hour playthrough, and added a few items of your posted compatibility list on Steam... curious to check them out.  

Do you guys need specific files?  Error reports?  I seem to remember the error prompts not being particularly useful.  Is there another useful bit to post?  My attempts to read between the lines and hunt down conflicts (without digging into code) have failed utterly.

Thanks in advance,
Kaz

**Comment by Theblessedwant** [comment]
First problem, thats because not all ammo has been updated to utilize RHA.
Second problem regarding purple boxes, its a dll issue that reroutes layers from the vanilla layer, a fix is coming that will address this and is already inside the main CE Branch.
I would need more info on the third issue, maybe an error log perhaps?

**Comment by KazTheMercenary** [comment]
If it's all known issues, that's perfect.  All seems to be Layer and Texture issues.  I'm not even positive it's that bad, it just LOOKS bad.

Looks like Vanilla Clothing Expanded (previously compatible) is showing signs and throwing error boxes.

Also looks like VGP - CoffeeTeaDrugs is throwing a fit about a generic distillery and wine must.  That hasn't been updated in some time, so I'm assuming it's the nomenclature again.

Gonna remove those two and see if it persists.  If so, I'll keep hunting.

Suggestion:  The Vanilla Expanded mod is wildly popular right now, and they're doing their own work on compatibility patches, but seem to be lagging behind (and they tie it to CE Main).  Maybe there is an inroad there?

Will attempt to reproduce my self-replicating socks and shoes  **chuckles**  Obviously that one was just odd, not particularly concerning.

**Comment by sumghai** [comment]
> The first being lack of armor penetration. I had my suspicions from play, but haven't been able to verify myself.

As of the most recent FastTrack update, all ammunition from the **_following_** categories have already been rebalanced to make use of the new `armorPenetrationSharp` and `armorPenetrationBlunt` stats:
* Grenades, launched
* Grenades, hand thrown
* High Caliber
* Industrial Misc
* Medieval
* Missile
* Neolithic
* Pistols
* Rifle
* Rocket
* Shell

The reason you may have heard of these issues is because the upstream CE project has only rebalanced armor penetration stats for a small fraction of CE ammo, as their focus is on supporting their own CE Guns and CE Melee packs; on the other hand, CE:FT has to also support third-party mods that use non-standard CE calibers not used by the aforementioned CE Guns/Melee mods, so it took some time (and quite a few updates) for the CE:FT team to rebalance and update all the stats ourselves (See #69 for details). 

There's still a few categories left, although those are usually exotic ammo types.

> The second is purple boxes for worn headgear.

This has already been fixed as of the FT-010 update. We pulled a workaround/bugfix from the upstream CE repo that disables a `GraphicsApparelDetour.DLL` found in many third-party apparel mods, as they are currently incompatible with CE's new apparel layers and rendered.

> The third being double equipment for certain things like gloves, scarves, eyeware... and attempting to remove them appears to duplicate them instead.

You'll need to be a bit more specific as to which other apparel mods this issue is happening in.

Finally, a couple of general comments:

* When you encounter an incompatibility, always do some basic troubleshooting first before reporting an issue. Start a new, temporary savegame with only Core and CE:FT, verify that there are no problems, then add your other mods one at a time until you find out which mod is causing the problem. It's tedious work, but it's the most reliable way to identify mod conflicts.

* Please only open one issue ticket per question/problem; mixing everything up into one ticket makes it harder to divvy up jobs amongst our (small) team, and our replies end up being very long because we have to respond to everything in one sitting.

**Comment by sumghai** [comment]
Most of the original issues have already been resolved in the past few updates, and there has been no further information/feedback from the reporting user.

Closing this until if and when the user gets back to us with the duplicate apparel issue.

**Comment by KazTheMercenary** [comment]
No problem at all.  I was only able to duplicate the scarf/goggle/head duplication.  Best I can tell, it seems like Rimsenal and Rimmu-Nation seem to be fighting for head-space  **laughs**  Will wear glasses with goggles.  Scarf with scarf with scarf.  Only seems to be one face filter.

Also, though this isn't this mod's problem, the naming/crafting/allowing conventions by those two mods (and anything else, really) clash pretty violently.  Each seems to want to put their own stuff under their own menu in their own way... making Allowing/Sorting a total pain in the ass.

Anyways, issue closed.  If any of these final comments are deemed new-issue-worthy, I'm happy to open up a new bit.
