### ISSUE TITLE
Incompatability with Show Hair w/ Hats

### ISSUE THREAD

**Issue by Xedict** [AthenaSulisMinerva/CombatExtendedFastTrack#164]
This is also a problem in the main CE branch, but I was wondering if there were any suggestions to be had here.

CE seems to be messing with how the Show Hair w/ Hats works. The functionality of the Show Hair mod seems borked with many hats, even those from other mods. I'm guessing this could be due to the recent change about multiple apparel layers on pawn heads.

**Comment by sumghai** [comment]
Unfortunately, since this is a product of the head apparel layer changes brought in from the upstream CE mod, there's not much the CE:FT team can do ourselves.

AFAIK, only NoImageAvailable's own [Don't Shave Your Hair mod](https://ludeon.com/forums/index.php?topic=36597.0) has been updated to be compatible with the new layers, so if you happen to be using a hair mod explicitly supported by DSYH, you can try that instead of SHWH.
