### ISSUE TITLE
[1.0.1.5-FT-001] Broken compatibility - AnimalCollabProj Patch Pack

### ISSUE THREAD

**Issue by ErdeFB** [AthenaSulisMinerva/CombatExtendedFastTrack#17]
The latest release at the time of writing, v1.0.1.5-FT-001 broke compatibility with said mod. Problem does not appear on version 1.0.1.3 of FT or the latest version of base CE version 1.0.1.5a.

AnimalCollabProj Patch Pack provides CE compatibility for AnimalCollabProject and includes a compatibility patch for A Dog Said as well.

I get the following kind of error whenever examining the information screen for any animal added by AnimalCollabProject:

```
Trying to get stat MeleePenetration from ACPWalrus which has no support for Combat Extended. Verse.Log:Error(String, Boolean)
CombatExtended.StatWorker_MeleeArmorPenetration:GetMeleePenetration(StatRequest)
CombatExtended.StatWorker_MeleeArmorPenetration:GetValueUnfinalized(StatRequest, Boolean)
RimWorld.StatWorker:GetValue(StatRequest, Boolean)
RimWorld.StatWorker:GetValue(Thing, Boolean)
RimWorld.StatExtension:GetStatValue_Patch1(Thing, StatDef, Boolean)
RimWorld.<StatsToDraw>c__Iterator1:MoveNext()
System.Linq.<CreateWhereIterator>c__Iterator1D`1:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:AddRange(IEnumerable`1)
RimWorld.StatsReportUtility:DrawStatsReport_Patch0(Rect, Thing)
Verse.Dialog_InfoCard:FillCard(Rect)
Verse.Dialog_InfoCard:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```

Workshop page:
https://steamcommunity.com/sharedfiles/filedetails/?id=1703449478

Wasn't sure if I should report this issue here, but since FT is supposed to be drop-in replacement for CE I chose to.

**Comment by Owlchemist** [comment]
Mod author here - problem is that the patch pack has a conditional check searching for any mod installed called Combat Extended. Since FastTrack operates under a different name, nothing happens.

**Comment by AthenaSulisMinerva** [comment]
@Owlchemist is correct.

The easiest way to fix this is for @Owlchemist to modify the patch pack's `PatchOperationFindMod` to search for both names, and run the subsequent PatchOps if _either_ are found:
```
<?xml version="1.0" encoding="utf-8" ?>
<Patch>
	<Operation Class="PatchOperationFindMod">
		<mods>
			<li>Combat Extended</li>
			<li>Combat Extended: FastTrack Edition</li>
		</mods>

		<!-- Rest of patch follows... -->
```
The other option would be to integrate the patch pack itself into CE:FT, and allow @Owlchemist full access to our repo so that he can push updates directly to us, although that depends on whether or not he is comfortable handing over distribution of his patches to us.

**Comment by ErdeFB** [comment]
That'd be an suboptimal solution as it would make FT a non drop-in replacement for CE and would require changes from other mod authors who utilize this method as well. I know brands are important, but so is compatibility. It's going to be a struggle for FT to gain popularity if a large portion of the available CE compatibility patches do not work with it.

**Comment by AthenaSulisMinerva** [comment]
By "drop-in" replacement for CE, we mean that CE:FT can be used on existing CE savegames without players having to manually edit class references.

The fact that we use a different mod name in the About.xml file isn't a mere branding/marketing gimmick, but an essentially legal one - if we continued to just call our fork "Combat Extended", users and mod manager systems would confuse it with the official CE project on Steam, and we'd invite the wrath of the original CE developers for unauthorized representation.

The long term goal of CE:FT is to include support for as many third-party as possible, so that people no longer need standalone compatibility patches. However, we prefer asking patch authors like @OwlChemist for permission to include their patches first, instead of just stealing them and be done with it. 

@sumghai is the one seeking out Steam authors for permission to bring in their patches, since I loathe (and don't use) Steam.

Ultimately, the final decision rests with @OwlChemist.

**Comment by sumghai** [comment]
@AthenaSulisMinerva - I asked @Owlchemist on Steam, and while he's not happy that we're not using the same mod name as the original CE, he's okay if we integrate his CE patches into our repo:

![Annotation 2019-07-14 065859](https://user-images.githubusercontent.com/4993380/61177326-2a864280-a605-11e9-947b-b8ee1d020cd0.png)

Since you don't use Steam, I'll pull the patches from there and add it to CE:FT - just be sure to give proper credit to Owlchemist.

**Comment by sumghai** [comment]
New AnimalCollabProj patches for CE:FT have been added. I've tested them and confirm that they work.

**Comment by AthenaSulisMinerva** [comment]
Cool, thanks.
