### ISSUE TITLE
Yes, Vehicles, Finally! is compatible!

### ISSUE THREAD

**Issue by NinjaSiren** [AthenaSulisMinerva/CombatExtendedFastTrack#183]
My mod, Yes, Vehicles, Finally! a vehicle and weapon mod that is compatible with vanilla Combat Extended is compatible with CE Fast Track. Tested and works fine!

Mod Link:
https://ludeon.com/forums/index.php?topic=48126
https://github.com/NinjaSiren/Yes-Vehicles-finally

**Comment by AthenaSulisMinerva** [comment]
We're perfectly happy for modders like yourself to integrate CE or CE:FT compatibility patches into your own mod itself.

However, the only mods we add to our mod compatibility list are mods that CE:FT has _**pre-bundled or built-in support for**_. Since your patches aren't bundled inside CE:FT, there is no need for us to explicitly say that CE:FT is compatible with the Yes, Vehicles! mod.

Instead, you can just mention in your own forums thread that your mod is compatible with both versions of CE.
