### ISSUE TITLE
XML Conflicts with <Mass> from Massivity mod

### ISSUE THREAD

**Issue by Tellik** [AthenaSulisMinerva/CombatExtendedFastTrack#185]
Linux Mint 19.2 - Cinnamon 4.2.4 (Kernel v. 4.15.0-70-generic)
RimWorld - 1.0.2408 rev750
CE:FT - 1.0.1.8-FT-011
[Massivity](https://steamcommunity.com/sharedfiles/filedetails/?id=1908867964) - 16NOV19 update

Massivity and CE:FT both add <Mass> to various material XML blocks of differing values. This causes red error duplicate XML node names in the block. I would expect in this case either one mod or the other to agree on mass, though I'm not sure how/why each mod uses mass calculations to come up with the numbers they have, or to override one or the other to prevent this error message depending on which mass value is more important.

https://pastebin.com/Ud2cMwjK

**Comment by robopitek** [comment]
(i copy and paste from my reply on my steam discussion
please contact with me on workshop if want)
[quote=Tellik;1740008852848371786]There is a conflict with duplicate Mass values appearing with use from Combat Extended: Fast Track. I raised an issue on their github with more details: https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/issues/185#issue-530774217 [/quote]
So we are have problem:
1 - I wrote in the description, for what is based my mass factor (Textiles base mass is 0.026 - mass of cloth. Metal/wood/stone base mass is 0.5 - mass of steel. Because they is do not mix)

2 - This red errors are not game breaking, they are only scary (but of course, it's good thing to repair this)

3 - Currently you can choose what mass factor is more importand, with the mods load order (while i put my mod higher from "Combat Extended: Fast Track", game the game calculated mass for things based of my mod, while i put "Combat Extended: Fast Track" above my mod, it was the opposite)

4 - There is a high probability that I will be able to do it on next Saturday (which doesn't mean I can fix it, if any)

5 - I don't know what the mass factor from "Combat Extended: Fast" is based (maybe this is balance maybe this is something other)

6 - Unfortunately, I may not be able to fix it because, I am not experienced as developers of "Combat Extended: Fast"

**Comment by AthenaSulisMinerva** [comment]
AFAIK, CE (and by extension, CE:FT) just uses fixed mass values for everything, whether explicitly defined in the original def xmls or updated via compatibility patches.

@sumghai, @Freedom187 and I can honestly say that the CE:FT team is far less experienced as developers than any other RimWorld modding group - we simply offer an easy-to-use fork with additional pre-bundled patches and ammo, while not touching any other underlying system where possible. So we wouldn't have any idea how to modify CE's core code to work with Massivity.

@Tellik and @robopitek, please try asking the original CE team instead.
