### ISSUE TITLE
Slow arrows problem (Info added!)

### ISSUE THREAD

**Issue by Nutellaschmier** [AthenaSulisMinerva/CombatExtendedFastTrack#203]
Hey, so I saw that the slow mortar shells were fixed, not got around to testing it with this colony yet, but the arrows of the tribals are still (of some bows) very slow, which makes the tribal raids a total joke. A 20 tiles further away pawn needs about 10-12 seconds to be hit with a arrow, allowing you to see it slowly falling dawn and then just moving a tile away, while the whole tribal army is already dead, and thats a little frustrating. It only affects the arrows so far, since I trust on you fixing the slow mortar if you said so. Maiby you can test it one time for yourself in a game if thats the case or a bug on my side, looking in my console I may saw errors, but none comlpaining about that. It is working fine, but just way to slow. Also if anyone else knows something about that, feel free to answer.

Thanks in advance.
Greetings,

Joel

The Game Version is: "1.0.2408 (64-Bit)"

The Mod Version (Using Steam Version, not a local Folder over Github, scared to break all third party mod with that), the Steam Version is: "v1.0.1.8-FT-012" with the latest update of Decem. 13, 14:43 German Time.

**Comment by sumghai** [comment]
@Nutellaschmier, could you please provide the game and mod version information, as described in [the posting guidelines](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/issues/175)?

**Comment by Nutellaschmier** [comment]
The Game Version is: "1.0.2408 (64-Bit)

The Mod Version (Using Steam Version, not a local Folder over Github, scared to break all third party mod with that), the Steam Version is: "v1.0.1.8-FT-012" with the latest update of Decem. 13, 14:43 German Time.

**Comment by sumghai** [comment]
Thank you for updating this issue with the requested version information.

We'll look into this further once we have time.

**Comment by Nutellaschmier** [comment]
Sure, dont haste, its a awesome mod after all and I hihgly appreaciate all the greate work you do everyday in the workshop

**Comment by AthenaSulisMinerva** [comment]
The current speed of arrows in CE:FT is fairly accurate in the context of RimWorld's simulation.

* Arrows [in real life](http://www.soarvalleyarchers.com/faqs/how-fast-can-an-arrow-travel/) only reach speeds of up to **70\~90 m/s**, and longbow arrows are even slower due to their weight

* In comparison, a 9x19mm Parabellum bullet can reach speeds of around **350\~380 m/s**, and many rifle bullets can travel twice or three times faster

* RimWorld (and CE / CE:FT) makes projectiles _look_ like they're travelling slower than real life for gameplay reasons, by scaling down _**all**_ projectile speeds uniformly by a factor of 0.2; if projectiles in CE or CE:FT traveled at their actual real-world speeds in RimWorld, _**every**_ projectile will zip across the entire length or width of your typical 250x250 or 300x300 in less than a second (taking into account that the average computer screen is physically less than one meter wide)

* Using [the standard CE calculation spreadsheet for projectiles](https://docs.google.com/spreadsheets/d/1-y3KCuTM_vJnxw-gQPl5KIiz7ySd7fw9P6Wx4zB5bZg/edit?usp=sharing) to rebalance all ammo for simulation in RimWorld, arrows are always going to be much slower than firearms

As for why we can't (or rather, won't) simply "fix" this:

* Simply increasing the speed values of the arrow ammo defs would throw them out of balance compared to bullets, rockets and cannon shells

* The mortar fix sumghai brought over from the upstream CE mod works by altering the gravity modifier of mortar shells; this is because mortars are indirect-fire artillery, which travel through the air in an parabolic or elliptical trajectory before gravity pulls them down to the ground (and hopefully their target); if we apply that gravity fix to the arrows, they would most likely just drop to the ground right in front of the archer pawn without travelling very far

See NoImageAvailable/CombatExtended/issues/941 in the original CE mod GitHub issue tracker for a similar analysis of why thrown grenades fly slowly in RimWorld.
