### ISSUE TITLE
Chicken Plucker's Rimmu-Nation & Red Horse Mods - Update all gun and melee tool stats

### ISSUE THREAD

**Issue by skycrossercat** [AthenaSulisMinerva/CombatExtendedFastTrack#208]
CE:FT version: 1.0.1.8-FT-012(latest release version
Rimworld version:1.0.2408
It seems rimmu-nation's weapon don't have the new melee armor penetration value, all their melee armor penetrations are 0.

**Comment by sumghai** [comment]
Yup!

In fact, all weapons from the Rimmu-Nation and Red Horse Faction packs need to have both their melee tools and gun stats overhauled to the new CE 1.6/1.8 standards.

Also, IIRC, RN currently ignores CE:FT's crafting recipe adjustments.

Would you like me to rename this issue to also cover gun stats?

**Comment by skycrossercat** [comment]
> Would you like me to rename this issue to also cover gun stats?

Sure thing, appreciate your effort.

**Comment by sumghai** [comment]
I've updated the guns and melee tools stats for Rimmu-Nation Weapons to the new CE 1.6/1.8 armor penetration system.

The next thing to do is to go through all of our existing Red Horse Faction mods, and make sure those have been updated too. Since most weapons from the various RH factions are simply copy & paste from the main RN Weapons library, this should be relatively faster than the one week it took to recalculate, double-check and overhaul said library.

I've also going to see if I can experiment with getting rid of the "If-RN-Weapons-is-also-installed-alongside-a-RH-Faction-mod" conditional patches, as those were getting cumbersome to maintain. This is based on my observations of how `CombatExtended.PatchOperationMakeGunCECompatible` operates, although I don't know if two (or more instances of that PatchOp attempting to patch the exact same defName would cause duplicate node errors.

**Comment by sumghai** [comment]
I think I can safely consider this done.

There are a few other CP/RH/RN mods not included as part of this overhaul, because they are either new mods that have never been patched before (e.g. SOTL, Doom) or are existing mods that have been extensively renamed/restructured such, that they may as well also be considered new mods (e.g. RH Furniture FBI update, Last Man Mercs renamed to Last Man Contingent)
