### ISSUE TITLE
Balance issue about Devastator mortar from MVT

### ISSUE THREAD

**Issue by skycrossercat** [AthenaSulisMinerva/CombatExtendedFastTrack#213]
CE-FT version:1.0.1.8-FT-012 (latest)
Rimworld version:1.0.2048 (latest)
The CE-FT patched Devastator mortar has a extremely long 1 minute cooldown between each burst just like vanilla mortar. It's quite weird to see they reload 25 shells in 5 seconds but stand there and do nothing for a minute after each burst, this would make the 25 shells container quite useless 'cause fights in rimworld don't last for too long. 
Maybe increase the reload time (30-40seconds maybe) to make it has more blank after it dump all the shells (or decrease the mag size) , but decrease the cooldown time between each burst (10-20 seconds) would be more balanced as a late game powerful weapon.

Edit: Found this at the Core Patch of vanilla mortar, maybe this the point of this?
`<turretBurstCooldownTime>2</turretBurstCooldownTime>`

**Comment by sumghai** [comment]
I definitely agree that the cooldown time should reduced.

In fact, I'm not even sure why the stock CE 81 mm mortar has such a long cooldown in the first place - IIRC regarding real-life semi-automated mortars, they re-adjust their aim quite quickly between rounds, and even the act of firing involves servos picking up and dropping mortar shells tail-first down the tube to fire - which definitely falls into the 30~45 second ballpark.

Maybe the extended delay us so that raider AI siege mortars don't fire too quickly before the player has a chance to organize a counterattack?

(Also, apologies for the late response. The Wifi in the entire dorm building has been down for three days now, and I'm limited to ultra-shitty mobile internet).

**Comment by skycrossercat** [comment]
I think there's no big problem about standard CE mortar, its cooldown is reduced to 2s, but keeps the aiming time for balance. If it do the mortar barrage like real life, that would be a disaster to players colony when sieged, also it is too powerful as a mid game weapon.
All we need is reduce the extremely long and non-sense "cooldown" of some weapons, but also keep the purpose of balancing.(devastator mortar is a late game weapon, so it should have it's advantages compare to standard one, not only a single-used 5 bursts shot)

**Comment by sumghai** [comment]
Okay, I see where the problem is now.

For the standard mortar, the `turretBurstCooldownTime` is 28 seconds for vanilla, which CE reduces to 2 seconds.

For MVT's Devastator mortar, the `turretBurstCooldownTime` is 60 seconds for vanilla (just as what you reported, @skycrossercat), which CE:FT currently hasn't patched.

Taking into consideration that the Devastator mortar is a late-game weapon, and assuming we scale the cooldown time relative to the CE-patched standard mortar, our theoretical updated cooldown time should be (60 / 28) * 2 ≈ 4.285714 s - a little over twice as long.

I'll round this up to 5 seconds, as 10 seconds might actually be too long compared to the standard mortar.

**Comment by sumghai** [comment]
After a bit of playtesting, I've increased the MVT Devastator mortar's cooldown time to 15 seconds.

This should be a good balance as it takes into account that the Devastator only needs to be reloaded once every 25 rounds (in five five-round salvos), and the amount of time it takes the mortars to reach the edge from a turret based in the center of a 250x250 cell map.

**Comment by sumghai** [comment]
Another easy win for the next update.
