### ISSUE TITLE
Sudden crash during Android v. tribal raid combat

### ISSUE THREAD

**Issue by tannerne** [AthenaSulisMinerva/CombatExtendedFastTrack#215]
My game crashes in the middle of shooting at tribal raid—I've drafted three Droids from Androids, a Battle Droid with a Rebel rifle and two worker droids with a Mossberg 500 and Taurus Judge respectively. The crash occurred twice, once in the initial raid and reloading from the (pre-raid) autosave after crashing. On a second reload, a pirate raid spawned instead, and the single raider was downed without incident. The first two crashes appeared to happen perhaps immediately after downing the second tribal in a four-person raid—maybe a result of beginning to flee?

I hope you'll be able to make some sense of the log, and I apologize if I'm looking at the wrong mod. I'm running CE:FT 1.0.1.5a on MacOS 10.15.2 with Rimworld 1.0.2408 (64-bit).

This crashing issue reoccurs sporadically, several seconds into an otherwise normal raid, though almost all combat happens without incident—perhaps a sudden crash one in ten raids at the very most. I haven't been able to draw any conclusions as a result, but please let me know if there's any more useful information I can provide.

Here's the most recent [Player.log](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/files/3992206/Player.log)

**Comment by AthenaSulisMinerva** [comment]
Crash logs aren't really useful to us, because it's far too difficult to comb through lines of error messages to figure out what they mean.

Have you tried the basic troubleshooting steps of stripping your installation down to only Core, CE:FT and the one or two mods you suspect are causing the problem?

Also, CE:FT 1.0.1.5a is *not* a valid version number - we are already on the FT-012 patch release (which is based on CE 1.8+), so please make sure you have updated to the latest version before attempting to reproduce this problem.

**Comment by tannerne** [comment]
My apologies, I misidentified CE as the mod to blame when it's really Desynchronized fighting with Real Fog of War (described [here](https://github.com/Vectorial1024/Desynchronized/issues/22)). Sorry for the inconvenience, and merry Christmas!
