### ISSUE TITLE
[RH] Faction: Umbra Company (1.0) - BTR-70 and KPV HMG added

### ISSUE THREAD

**Issue by ChickenPluckers** [AthenaSulisMinerva/CombatExtendedFastTrack#219]
Guess who's back.
Still, taking my time to update my mods, and I still got love for the streets it's the C and P.

Hey guys added these two major things to Umbra Company:
Race: RHRace_BTR70_APC
Pawntype: RHMech_BTR70_APC_UC

Weapon: RHGun_KPV_HMG

I'm assuming you two are on leave already and are super busy so my apologies. Take care!

**Comment by AthenaSulisMinerva** [comment]
You will have to wait until sumghai has stable internet access again before he can look into your issue.

Also, while I have been known to sound very harsh at times - please don't joke about sumghai's internet problems. He is currently (and temporarily) living in a place with heavy internet restrictions, and could get into some very serious and life-threatening trouble because of your comments.

**Comment by ChickenPluckers** [comment]
Hello. Sorry I didn't realise his situation is like that, it's the kind of thing I haven't encountered before so I apologise. Will wait, hope he'll be okay. Take care

**Comment by sumghai** [comment]
Implemented in #200.
