### ISSUE TITLE
Missing pull request from upstream CE

### ISSUE THREAD

**Issue by skycrossercat** [AthenaSulisMinerva/CombatExtendedFastTrack#246]
Remove Slash
https://github.com/NoImageAvailable/CombatExtended/pull/917
Remove melee building modifiers
https://github.com/NoImageAvailable/CombatExtended/pull/916
Fix fire never spreading while zero wind or indoors 
https://github.com/NoImageAvailable/CombatExtended/pull/923
Misc fixes
https://github.com/NoImageAvailable/CombatExtended/pull/927

So far I find these pull requests from upstream are missing in current CE:FT upstream repos (already check CE:FT master branch and confirm). Some of them have significant effects on gameplay.
(about the 'remove slash', it seems base ce team decided to replace all the 'slash' type damage to new 'scratch' type tool, may need to check if any patches handled by CE:FT using such tool)

**Comment by AthenaSulisMinerva** [comment]
Those PRs were only accepted into CE's **_Development_** branch, not their **_master_** branch.

To minimize stability issues between major CE updates, CE:FT generally only keeps itself up-to-date with the **_master_** branch, and at the time of writing we are up-to-date with their **_master_** branch, with our own changes on top of that - if we were missing any PRs, the following message on our repo homepage would actually tell us how many commits we are _behind_ on:

![Annotation 2020-01-13 184650](https://user-images.githubusercontent.com/49829079/72249802-17e0da80-3635-11ea-934a-735d5e92c9b3.png)

In theory, the CE:FT team could manually port fixes from the CE dev branch, but it is painstaking work and the original changes from CE could easily be reverted at short notice by CE's senior management - for instance, apparently one of sumghai's submissions was accepted and then immediately reverted rather than rejected outright, with the exact same fix by an official CE contributor later accepted permanently.

So until those changes reach the main CE master branch, we're not going to pre-emptively bring them over.
