### ISSUE TITLE
Patch for Vanilla Furniture Expanded - Security

### ISSUE THREAD

**Issue by SamuraiKenshi** [AthenaSulisMinerva/CombatExtendedFastTrack#249]

**Comment by AthenaSulisMinerva** [comment]
As per the issue reporting guidelines, please provide a link to the original mod on GitHub or Steam Workshop.

**Comment by SamuraiKenshi** [comment]
https://rimworldbase.com/vanilla-furniture-expanded-mod/ Link to mod.

**Comment by SamuraiKenshi** [comment]
Link to mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007

**Comment by skycrossercat** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1965337447
Already a patch on workshop, but it seems the artillery map strike can't work now.

**Comment by SamuraiKenshi** [comment]
When I use this patch world map won't generate.

**Comment by SamuraiKenshi** [comment]
I use Combat Extended Fast Track

**Comment by skycrossercat** [comment]
If you got problems about the patch, you should ask a solution at the patch's bug report section instead of here. I only provide you a approach to let the mod work with CE.
And mostly, the author would test their patch before release. The map geneartion or other serious issues are more likely to cause by incorrect load order or mod conflicts.

**Comment by AthenaSulisMinerva** [comment]
Duplicate of #70
