### ISSUE TITLE
Loading Bench, no bills for certain ammo types.

### ISSUE THREAD

**Issue by MajorMonotone** [AthenaSulisMinerva/CombatExtendedFastTrack#265]
Hi all,

Have a problem with bills for certain ammo types not appearing on the loading bench menu even though I have guns that require those ammo types (9mm, 5.45x39, .50bmg etc) I'm using mods like Rimmunation, Turret Collection and Defensive Machine Gun Turret Pack. I am also using a whole heap of other mods but they shouldn't add any weaponry but I could be wrong. I'm not sure whether its a compatibility issue or maybe a mod loading order?

Sorry for any bother caused by this.

**Comment by sumghai** [comment]
Since you're experiencing multiple problems with multiple mods, I strongly recommend you first perform some basic troubleshooting, as per the [issue reporting guidelines](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/issues/175):

* Remove all your other mods first

* Verify that Core and CE:FT alone works fine

* Add and test only one of the problematic mods at a time

* Come back to us when you have specifically identified each of the guns and ammo affected (we can't really work off "etc.", in case we miss something)

**Comment by AthenaSulisMinerva** [comment]
Closing as user failed to follow up.
