### ISSUE TITLE
More Vanilla Turrets 1.0

### ISSUE THREAD

**Issue by RoronoaDroagon** [AthenaSulisMinerva/CombatExtendedFastTrack#29]
Have done some testing and tryd to get the said mod: More Vanilla Turrets 1.0  https://steamcommunity.com/sharedfiles/filedetails/?id=1478936958 
to work with CE both with the xpath and with making the mod definitions with CE definitions and i'm hiting the same issue: pawns stuck when reloading turrets, both mand and unmaned.
I'm far from any expert or got enough knowlege about coding to be able to fix the issue.
It would be awesome if you guy's got it to work with CE since the turret mod is used by over 130k people me included.
It's a very used and lovely mod as with this version of CE.
I have made a own ammo for the Cannon turret if you guy's want it for shortening down the time/work needed?
Love this "version" of CE since it's more "friendly" towards other mods and that you guy's are alot more active and doing stuff that is noticable when it comes to other mods.
Keep up the good work and know that we appreciate the time and effort you guy's take and use on and for this project/mod "version".

**Comment by sumghai** [comment]
I'll take a look once I'm done with the Glitter Tech patches.

**Comment by RoronoaDroagon** [comment]
Awesome.
It's just to say if you want the 20mm cannon round file i made for it....??
I figured it's a 20mm vulcan cannon but it was just a temp to see.
I appreciate you guy's taking the time to do thees kind of things.
I know alot of people don't see the time and effort put in to all the patches and fixes.
And i can't say it enough but: keep up the good work and that there is people out here that really appreciate what you guy's do.

**Comment by sumghai** [comment]
Okay, these are patched and ready to go.

Summary:
* **Gun Complex** is based on the M2HB .50 cal. machine gun
* **Rocket Complex** is based on the Mk 153 SMAW rocket launcher; the original weapon is a single-shot reloadable shoulder-fired launcher, while the MVT version has a magazine capacity of five rockets to emulate pawns keeping a small supply of rockets at the complex (so that they don't need to run back to the armory after every shot)
* **Military Grade Turrets (manual and auto)** are based on the twin-mount version of the M2HB .50 cal. machine gun
* **Shredder Turrets (manual and auto)** are based on real-life prototypes of Metal Storm weapons; for simplicity, I treated them like rapid-fire multibarrel shotgun turrets
* **Precision Turrets (manual and auto)** are based on the M242 Bushmaster autocannon, with a new **25x137mm NATO** ammo definition
* **Blast Turrets (manual and auto)** were originally meant to throw three time-delayed frag grenades, but CE doesn't allow hand grenades to be loaded as turret ammunition; instead, I turned the Blast Turrets into a stripped-down version of the real life Mk19 automatic grenade launcher, with the MVT version locked to firing a three-round salvo of 40x53mm grenade rounds at a time
* **Vulcan Cannons (manual and auto)** are based on the M61 Vulcan gatling-style rotary cannon, with a new **20x102mm NATO** ammo definition
* **Devastator Mortar** is based on the vanilla base game's 81mm mortar launcher, with a new **81mm mortar shell (Plasma)** ammo and damage subtype

All ammo should also be craftable from the hand-loading and/or machining workbenches.
