### ISSUE TITLE
Android Tiers CE Patch

### ISSUE THREAD

**Issue by NMJohns** [AthenaSulisMinerva/CombatExtendedFastTrack#30]
Already exists here: https://steamcommunity.com/sharedfiles/filedetails/?id=1386530536

Can this be included in the CEFT  base mod?

**Comment by sumghai** [comment]
I'll take a look once I'm done with the Glitter Tech patches.

**Comment by NMJohns** [comment]
Is there anything I can do to assist? I really like this mod. I understand XML. Is there a guide I can check out to help with the refactoring of some of these patches?

**Comment by sumghai** [comment]
@NMJohns - Just sit tight until I've refactored the patches. I will then ask you to test them.

**Comment by sumghai** [comment]
I'm currently making good progress integrating Saebbi's patches, but there are still quite a few things I need to do:

* **New ammo defs** - the original patches come pre-bundled with Android Tiers-unqiue ammo for the M7 Mech weapons, but I'd like to instead define some real-world high-caliber ammo that can also be used with other third-party mods:
  * 40MM Cannon could be based on the 40x365mm Bofors AA rounds
  * Mastiff Shotgun could use a 120mm canister shot tank shell (essentially a cannon shell with buckshot)
  * Both the Hand Cannon and Anti-Mech Rifle would share the same ammo, although I haven't figured out a real-life cartridge that could be used
* I need to adjust the M7 Mech's carry bulk and weight capacities, so that they can actually carry a decent amount of ammo for whatever weapons they are armed with on spawn
* The Swarm Mortar round needs to be defined as a dynamically-patched CE ammo item and projectile

**Comment by sumghai** [comment]
I'm almost finished patching this mod, but there's a small problem.

After the micro-scythers spawned from the nanoswarm shell defeat their first target, the Debug log starts getting flooded with errors:

```
JobDriver threw exception in initAction for pawn MicroScyther159479 driver=JobDriver_WaitMaintainPosture (toilIndex=0) driver.job=(Wait_MaintainPosture (Job_98282)) lastJobGiver=null
System.NullReferenceException: Object reference not set to an instance of an object

JobDriver threw exception in initAction for pawn MicroScyther159479 driver=JobDriver_Wait (toilIndex=0) driver.job=(Wait (Job_98283)) lastJobGiver=null
System.NullReferenceException: Object reference not set to an instance of an object

An error occurred while starting an error recover job. We have to stop now to avoid infinite loops. This means that the pawn is now jobless which can cause further bugs. pawn=MicroScyther159479
```

I have a feeling it's to do with the different behavioral logic behind the Micro-Scythers, but I can't quite figure out what it is.

**Comment by sumghai** [comment]
I've sent @Freedom187 a message, to see if he has any ideas.

**Comment by sumghai** [comment]
@Freedom187 suspects the problem has something to do with the micro-scyther's ThinkTree. He's investigating how other mods with similiar critters deal with this issue.

In the meantime, he asked me to do some more testing, and I reproduced the JobDriver bug under the following conditions:
* New savegame, mod load order: Core, JecsTools, Humanoid Alien Races, Android Tiers, CE:FT
* New savegame, mod load order: Core, JecsTools, Humanoid Alien Races, Android Tiers

I was pretty surprised by the second scenario, since I previously tested it with no problems without CE:FT.

In either case, I'm going to try contacting AT's author Atlas with my bug report, and see what he/she makes of it. Worse case scenario, CE:FT may have to simply disable nanoswarm shells altogether.

@AthenaSulisMinerva, apologies if this delays FT-005.

**Comment by AthenaSulisMinerva** [comment]
That's okay @sumghai - I'll trust your (and @Freedom187's) judgement on this one. Just let me know via Hangouts when you're done.

**Comment by sumghai** [comment]
I got in touch with Android Tiers' author Atlas via Discord - he's having a little trouble with Steam lately, but will look into the micro-scyther issue as soon as he can.

In the meantime, I'm disabling the nanoswarm shells for now - we can always re-enabled it once the original mod has been fixed.

Otherwise, we're good to go on this one, @AthenaSulisMinerva.
