### ISSUE TITLE
Vanilla Armour Expanded & Vanilla Apparel Expanded

### ISSUE THREAD

**Issue by ErusCormag** [AthenaSulisMinerva/CombatExtendedFastTrack#34]
https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282

https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817

The mod author says that compatibility is built into the github version of CE but I don't think they were talking about CEFT.

**Comment by AthenaSulisMinerva** [comment]
I had a look at the original CE repo on GitHub, and it turns out that the CE patches for those two mods are in the (unreleased) **_development_** branch, instead of the master branch where releases normally come from. In order words, the author announced compatibility before it was officially available, and even then pointed to the wrong location.

We'll wait until CE officially releases their next update before folding their changes into our repo (regardless of whether or not their changes make it before our next FastTrack release).
