### ISSUE TITLE
Game crashes when loading with RH Faction mods

### ISSUE THREAD

**Issue by Loboo** [AthenaSulisMinerva/CombatExtendedFastTrack#43]
game crashes when i try to load RH factions, no matter which one. First takes a lot to load (While loading crashes sometimes) sometimes loads but crashes during the world selection.
Any solution? 
If theres not i still have to thank your team for doing such hard work as working with CE.

**Comment by AthenaSulisMinerva** [comment]
@sumghai - You're familiar with Rimmu Nation. Thoughts?

**Comment by sumghai** [comment]
@Loboo - you will need to determine the cause of your problem via a process of elimination:

1) Try starting a new savegame with only Core and CE:FT; confirm that there are no crashes
2) Add **one** (only **one**) of your RH mods, start another new savegame and check
3) Repeat (2) for each of the RH faction mods

**Comment by Loboo** [comment]
thanks for answering! I done that and they actually work pretty well. The problems starts if i put more than one faction, or other mods (No matter wich ones it breaks the game atfer a couple ones, even cosmetics)

 So, something that i want to ask 
This could be related to the pc specs? (Wich im not gonna lie its pretty potato quality) 
Thanks for answering again ^^

**Comment by sumghai** [comment]
Have you tried loading multiple RH factions _without_ CE:FT?

If you could tell us what happens when you do that, then we can definitively determine whether it's to do with your PC not being able to handle multiple mods in general, or CE:FT not being able to handle multiple RH factions (the last of which is unlikely, given that while I was developing RH patches, I did in fact have multiple factions running under CE:FT with no issues).

**Comment by sumghai** [comment]
Closing due to lack of response
