### ISSUE TITLE
Red Horse: British Military and Elite Crew

### ISSUE THREAD

**Issue by ChickenPluckers** [AthenaSulisMinerva/CombatExtendedFastTrack#48]
Alright, what's up legends. This is for the Red Horse issues with two mods innit fam.

British Military Kit is finished. End of dit, fair one. Let's have a patch quicktime bruv

Elite Crew has the following new weapons:

From file: RN_RangedIndustrialGrenades.xml
RNThrown_RGDNade
RNThrown_PUBGVodka
RNThrown_C4CSGO_Elite

From file: RN_MeleeNeolithic.xml
RNMeleeWeapon_Knife_Skinner

**Comment by AthenaSulisMinerva** [comment]
@sumghai - Since you and I are both big fans of RN, this should be your number one priority (once you're less busy with your day job, that is).

**Comment by sumghai** [comment]
Unfortinately, we're pausing work on patches while we prioritize coordinating with the original CE team on integrating CE 1.6's armor and projectile revamp.

Sorry!

**Comment by sumghai** [comment]
Okay, now that I have a bit more free time to look at this in detail...

## Elite Crew grenades
As per the precedent set by @Freedom187, we would actually disable most of the Elite Crew grenades, since the generic frag and molotov grenades that are included with CE/CE:FT already fit the bill.

For the C4 explosive, we can easily reuse one of our existing patches from another faction.

## Elite Crew Skinner Knife
Since I've never patched melee weapons before, I'll take a look to see if we can reuse the stats from the CE Melee pack; otherwise, I'm going have to recalculate the values from scratch using the CE spreadsheet.

## Red Horse: British Military
Leaving this for the next update after this one.

**Comment by sumghai** [comment]
Knife patched and tested OK - kills rodents with a single stab, while several stabs and slashes are needed against a typically-clothed raider.

**Comment by sumghai** [comment]
I lied, @ChickenPluckers. You're getting Her Majesty's Finest in this upcoming update.

God Save The Queen!
