### ISSUE TITLE
Mod: Combat Extended Fixes Partial Integration?

### ISSUE THREAD

**Issue by githubuser1256** [AthenaSulisMinerva/CombatExtendedFastTrack#62]
Are you aware of the Combat Extended Fixes mod? I think at least one of his changes is a bugfix e.g. Minigun capacity dropped to 500, 250shot burst, so you can actually reload it properly.

**Comment by AthenaSulisMinerva** [comment]
Yeesh, those "fixes" are more like personal tweaks. And I have no idea what that DLL is supposed to do.

Thoughts, @sumghai?

**Comment by sumghai** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1776175645

The author even name-dropped CE:FT.

That mystery meat DLL changes various CE behaviours:
- Eliminates bulk from ammunition in firearm magazines
- Loadouts as "positive item lists" (i.e. existing non-loadout items don't get dumped from inventory)
- Changes suppression mechanic so that pawns will eventually hunker down but never run away
- Allows pawns with shield belts to operate manned turrets (this will get fixed in the original CE project anyway)

I think functionality bugfixes should be submitted to the original CE, while CE:FT just deals with adding more compatibility patches.

**Comment by AthenaSulisMinerva** [comment]
Agreed - Closing.

@sumghai, tell the author what you just said here.
