### ISSUE TITLE
Vanilla Expanded security patch request

### ISSUE THREAD

**Issue by rawrfisher** [AthenaSulisMinerva/CombatExtendedFastTrack#70]
https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007

That should be the link

**Comment by Taranchuk** [comment]
Patch in development. If you want it now, but with bugs, here is the link: https://github.com/onigamii/VanillaFurnitureExpanded-SecurityCE

**Comment by rawrfisher** [comment]
Any imporvment is better then nothing lol

**Comment by AthenaSulisMinerva** [comment]
This is now being [handled by a third-party as a standalone patch mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1965337447), and since the compatibility involves Harmony patching of assemblies, this falls outside CE:FT's area of responsibility.

Also @sumghai fixed an assembly version number issue in FT-014, so any issues are now wholly on the third-party patch author's end.

Marking this one as done.
