### ISSUE TITLE
Cannot craft ammo for Glitter Tech weapons

### ISSUE THREAD

**Issue by Sabersenpai** [AthenaSulisMinerva/CombatExtendedFastTrack#86]
How do we make ammo for rail guns? the ammo is in the Def for it but not set to a crafting table. the only way I can really get ammo for any 6mm, 8mm, 12mm sabot rounds is via the admin consol.

**Comment by sumghai** [comment]
Oooh, right - I didn't make any of the Glitter Tech ammo craftable, since GT's author _Sam claimed that none of the GT weapons themselves are currently craftable by colonists, but I forgot that players do, in fact, salvage weapon drops from raiders.

Also, since I've genericized both the plasma and railgun ammo (so that other mods can use them), I really should make them craftable anyway.

**Comment by sumghai** [comment]
@Sabersenpai, please test the following WIP version of CE:FT :

https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/archive/4566d3e0d295ad6832a38fd8824bcf1ce442be3d.zip

Both the railgun cartridges and plasma power cells should now be craftable from the Machining Table. Plasma power cells additionally requires players to unlocked the **Pulse charged munitions** research project.

I decided not to exclusively bind railgun and plasma ammo crafting to just GT buildings, as other non-GT mods may use these ammo types in the future.

**Comment by Sabersenpai** [comment]
Thanks alot!

**Comment by Sabersenpai** [comment]
Yes they do work now, I also like the price you used being a sabot having uranium and steel was a good move!
